// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package urlshorterservice

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLShorterService creates a new instance of MockURLShorterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLShorterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLShorterService {
	mock := &MockURLShorterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLShorterService is an autogenerated mock type for the URLShorterService type
type MockURLShorterService struct {
	mock.Mock
}

type MockURLShorterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLShorterService) EXPECT() *MockURLShorterService_Expecter {
	return &MockURLShorterService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockURLShorterService
func (_mock *MockURLShorterService) Generate(ctx context.Context, url string) (string, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShorterService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockURLShorterService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockURLShorterService_Expecter) Generate(ctx interface{}, url interface{}) *MockURLShorterService_Generate_Call {
	return &MockURLShorterService_Generate_Call{Call: _e.mock.On("Generate", ctx, url)}
}

func (_c *MockURLShorterService_Generate_Call) Run(run func(ctx context.Context, url string)) *MockURLShorterService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLShorterService_Generate_Call) Return(s string, err error) *MockURLShorterService_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLShorterService_Generate_Call) RunAndReturn(run func(ctx context.Context, url string) (string, error)) *MockURLShorterService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateBatch provides a mock function for the type MockURLShorterService
func (_mock *MockURLShorterService) GenerateBatch(ctx context.Context, urls []string) ([]string, error) {
	ret := _mock.Called(ctx, urls)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBatch")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(ctx, urls)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(ctx, urls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, urls)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShorterService_GenerateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBatch'
type MockURLShorterService_GenerateBatch_Call struct {
	*mock.Call
}

// GenerateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - urls []string
func (_e *MockURLShorterService_Expecter) GenerateBatch(ctx interface{}, urls interface{}) *MockURLShorterService_GenerateBatch_Call {
	return &MockURLShorterService_GenerateBatch_Call{Call: _e.mock.On("GenerateBatch", ctx, urls)}
}

func (_c *MockURLShorterService_GenerateBatch_Call) Run(run func(ctx context.Context, urls []string)) *MockURLShorterService_GenerateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLShorterService_GenerateBatch_Call) Return(strings []string, err error) *MockURLShorterService_GenerateBatch_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockURLShorterService_GenerateBatch_Call) RunAndReturn(run func(ctx context.Context, urls []string) ([]string, error)) *MockURLShorterService_GenerateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function for the type MockURLShorterService
func (_mock *MockURLShorterService) GetOriginalURL(ctx context.Context, id string) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShorterService_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type MockURLShorterService_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockURLShorterService_Expecter) GetOriginalURL(ctx interface{}, id interface{}) *MockURLShorterService_GetOriginalURL_Call {
	return &MockURLShorterService_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", ctx, id)}
}

func (_c *MockURLShorterService_GetOriginalURL_Call) Run(run func(ctx context.Context, id string)) *MockURLShorterService_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLShorterService_GetOriginalURL_Call) Return(s string, err error) *MockURLShorterService_GetOriginalURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLShorterService_GetOriginalURL_Call) RunAndReturn(run func(ctx context.Context, id string) (string, error)) *MockURLShorterService_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}
