package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const (
	projectRoot    = "../../"
	genComment     = "// generate:reset"
	goFileSuffix   = ".go"
	genFileSuffix  = ".gen.go"
	testFileSuffix = "_test.go"
	genFileName    = "reset.gen.go"
	genHeader      = "// Code generated by reset generator; DO NOT EDIT.\n"
)

// Структура для хранения информации о найденной структуре
type structInfo struct {
	Name     string
	Fields   []*ast.Field
	TypeSpec *ast.TypeSpec
}

func main() {
	pkgs := map[string][]*structInfo{}

	// Сканируем все директории и ищем структуры с // generate:reset
	filepath.Walk(projectRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, goFileSuffix) || strings.HasSuffix(path, genFileSuffix) || strings.HasSuffix(path, testFileSuffix) {
			return nil
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil
		}

		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				st, ok2 := ts.Type.(*ast.StructType)
				if !ok || !ok2 {
					continue
				}

				if gd.Doc != nil {
					for _, c := range gd.Doc.List {
						if strings.TrimSpace(c.Text) == genComment {
							dir := filepath.Dir(path)
							pkgs[dir] = append(pkgs[dir], &structInfo{Name: ts.Name.Name, Fields: st.Fields.List, TypeSpec: ts})
						}
					}
				}
			}
		}

		return nil
	})

	for pkgDir, structs := range pkgs {
		if len(structs) == 0 {
			continue
		}

		genResetFile(pkgDir, structs)
	}
}

func genResetFile(pkgDir string, structs []*structInfo) {
	var buf bytes.Buffer
	pkgName := detectPkgName(pkgDir)
	buf.WriteString(genHeader)
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	for _, s := range structs {
		buf.WriteString(genResetMethod(s))
		buf.WriteString("\n")
	}

	outPath := filepath.Join(pkgDir, genFileName)
	formatted, _ := format.Source(buf.Bytes())
	os.WriteFile(outPath, formatted, 0644)
}

func detectPkgName(dir string) string {
	files, _ := os.ReadDir(dir)
	for _, f := range files {
		if !f.IsDir() && strings.HasSuffix(f.Name(), goFileSuffix) {
			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, filepath.Join(dir, f.Name()), nil, parser.PackageClauseOnly)
			if err == nil {
				return file.Name.Name
			}
		}
	}

	return "main"
}

func genResetMethod(s *structInfo) string {
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", s.Name))
	buf.WriteString("\tif s == nil { return }\n\n")

	for _, field := range s.Fields {
		for _, name := range field.Names {
			buf.WriteString(resetFieldCode("s", name.Name, field.Type))
		}
	}

	buf.WriteString("}\n")

	return buf.String()
}

// fieldRef формирует ссылку на поле с учётом того, что name может быть пустым
func fieldRef(parent, name string) string {
	if name != "" {
		return parent + "." + name
	}
	return parent
}

func resetFieldCode(parent, name string, expr ast.Expr) string {
	ref := fieldRef(parent, name)

	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "complex64", "complex128":
			return fmt.Sprintf("\t%s = 0\n", ref)
		case "string":
			return fmt.Sprintf("\t%s = \"\"\n", ref)
		case "bool":
			return fmt.Sprintf("\t%s = false\n", ref)
		default:
			// возможно вложенная структура
			return fmt.Sprintf("\tif resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil { resetter.Reset() }\n", ref, ref)
		}
	case *ast.StarExpr:
		// указатель
		ptrExpr := "*" + ref
		return fmt.Sprintf("\tif %s != nil { %s }\n", ref, resetFieldCode(ptrExpr, "", t.X))
	case *ast.ArrayType:
		// слайс
		return fmt.Sprintf("\t%s = %s[:0]\n", ref, ref)
	case *ast.MapType:
		return fmt.Sprintf("\tclear(%s)\n", ref)
	}

	return ""
}
