// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package urlcase

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLUseCase creates a new instance of MockURLUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLUseCase {
	mock := &MockURLUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLUseCase is an autogenerated mock type for the URLUseCase type
type MockURLUseCase struct {
	mock.Mock
}

type MockURLUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLUseCase) EXPECT() *MockURLUseCase_Expecter {
	return &MockURLUseCase_Expecter{mock: &_m.Mock}
}

// DeleteURLsAsync provides a mock function for the type MockURLUseCase
func (_mock *MockURLUseCase) DeleteURLsAsync(shortURLs []string, userID string) {
	_mock.Called(shortURLs, userID)
	return
}

// MockURLUseCase_DeleteURLsAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURLsAsync'
type MockURLUseCase_DeleteURLsAsync_Call struct {
	*mock.Call
}

// DeleteURLsAsync is a helper method to define mock.On call
//   - shortURLs []string
//   - userID string
func (_e *MockURLUseCase_Expecter) DeleteURLsAsync(shortURLs interface{}, userID interface{}) *MockURLUseCase_DeleteURLsAsync_Call {
	return &MockURLUseCase_DeleteURLsAsync_Call{Call: _e.mock.On("DeleteURLsAsync", shortURLs, userID)}
}

func (_c *MockURLUseCase_DeleteURLsAsync_Call) Run(run func(shortURLs []string, userID string)) *MockURLUseCase_DeleteURLsAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLUseCase_DeleteURLsAsync_Call) Return() *MockURLUseCase_DeleteURLsAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockURLUseCase_DeleteURLsAsync_Call) RunAndReturn(run func(shortURLs []string, userID string)) *MockURLUseCase_DeleteURLsAsync_Call {
	_c.Run(run)
	return _c
}

// Expand provides a mock function for the type MockURLUseCase
func (_mock *MockURLUseCase) Expand(ctx context.Context, id string) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Expand")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLUseCase_Expand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expand'
type MockURLUseCase_Expand_Call struct {
	*mock.Call
}

// Expand is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockURLUseCase_Expecter) Expand(ctx interface{}, id interface{}) *MockURLUseCase_Expand_Call {
	return &MockURLUseCase_Expand_Call{Call: _e.mock.On("Expand", ctx, id)}
}

func (_c *MockURLUseCase_Expand_Call) Run(run func(ctx context.Context, id string)) *MockURLUseCase_Expand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLUseCase_Expand_Call) Return(s string, err error) *MockURLUseCase_Expand_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLUseCase_Expand_Call) RunAndReturn(run func(ctx context.Context, id string) (string, error)) *MockURLUseCase_Expand_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockURLUseCase
func (_mock *MockURLUseCase) GetStats(ctx context.Context) (int, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 int
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockURLUseCase_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockURLUseCase_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockURLUseCase_Expecter) GetStats(ctx interface{}) *MockURLUseCase_GetStats_Call {
	return &MockURLUseCase_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockURLUseCase_GetStats_Call) Run(run func(ctx context.Context)) *MockURLUseCase_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLUseCase_GetStats_Call) Return(urls int, users int, err error) *MockURLUseCase_GetStats_Call {
	_c.Call.Return(urls, users, err)
	return _c
}

func (_c *MockURLUseCase_GetStats_Call) RunAndReturn(run func(ctx context.Context) (int, int, error)) *MockURLUseCase_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function for the type MockURLUseCase
func (_mock *MockURLUseCase) GetUserURLs(ctx context.Context, userID string) ([]URLPair, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []URLPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]URLPair, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []URLPair); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]URLPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLUseCase_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockURLUseCase_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockURLUseCase_Expecter) GetUserURLs(ctx interface{}, userID interface{}) *MockURLUseCase_GetUserURLs_Call {
	return &MockURLUseCase_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, userID)}
}

func (_c *MockURLUseCase_GetUserURLs_Call) Run(run func(ctx context.Context, userID string)) *MockURLUseCase_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLUseCase_GetUserURLs_Call) Return(uRLPairs []URLPair, err error) *MockURLUseCase_GetUserURLs_Call {
	_c.Call.Return(uRLPairs, err)
	return _c
}

func (_c *MockURLUseCase_GetUserURLs_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]URLPair, error)) *MockURLUseCase_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockURLUseCase
func (_mock *MockURLUseCase) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLUseCase_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockURLUseCase_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockURLUseCase_Expecter) Ping(ctx interface{}) *MockURLUseCase_Ping_Call {
	return &MockURLUseCase_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockURLUseCase_Ping_Call) Run(run func(ctx context.Context)) *MockURLUseCase_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLUseCase_Ping_Call) Return(err error) *MockURLUseCase_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockURLUseCase_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockURLUseCase_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Shorten provides a mock function for the type MockURLUseCase
func (_mock *MockURLUseCase) Shorten(ctx context.Context, rawURL string, userID string) (ShortenResult, error) {
	ret := _mock.Called(ctx, rawURL, userID)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 ShortenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (ShortenResult, error)); ok {
		return returnFunc(ctx, rawURL, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ShortenResult); ok {
		r0 = returnFunc(ctx, rawURL, userID)
	} else {
		r0 = ret.Get(0).(ShortenResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, rawURL, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLUseCase_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockURLUseCase_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - ctx context.Context
//   - rawURL string
//   - userID string
func (_e *MockURLUseCase_Expecter) Shorten(ctx interface{}, rawURL interface{}, userID interface{}) *MockURLUseCase_Shorten_Call {
	return &MockURLUseCase_Shorten_Call{Call: _e.mock.On("Shorten", ctx, rawURL, userID)}
}

func (_c *MockURLUseCase_Shorten_Call) Run(run func(ctx context.Context, rawURL string, userID string)) *MockURLUseCase_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockURLUseCase_Shorten_Call) Return(shortenResult ShortenResult, err error) *MockURLUseCase_Shorten_Call {
	_c.Call.Return(shortenResult, err)
	return _c
}

func (_c *MockURLUseCase_Shorten_Call) RunAndReturn(run func(ctx context.Context, rawURL string, userID string) (ShortenResult, error)) *MockURLUseCase_Shorten_Call {
	_c.Call.Return(run)
	return _c
}

// ShortenBatch provides a mock function for the type MockURLUseCase
func (_mock *MockURLUseCase) ShortenBatch(ctx context.Context, items []BatchItem, userID string) ([]BatchResult, error) {
	ret := _mock.Called(ctx, items, userID)

	if len(ret) == 0 {
		panic("no return value specified for ShortenBatch")
	}

	var r0 []BatchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []BatchItem, string) ([]BatchResult, error)); ok {
		return returnFunc(ctx, items, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []BatchItem, string) []BatchResult); ok {
		r0 = returnFunc(ctx, items, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BatchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []BatchItem, string) error); ok {
		r1 = returnFunc(ctx, items, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLUseCase_ShortenBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortenBatch'
type MockURLUseCase_ShortenBatch_Call struct {
	*mock.Call
}

// ShortenBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items []BatchItem
//   - userID string
func (_e *MockURLUseCase_Expecter) ShortenBatch(ctx interface{}, items interface{}, userID interface{}) *MockURLUseCase_ShortenBatch_Call {
	return &MockURLUseCase_ShortenBatch_Call{Call: _e.mock.On("ShortenBatch", ctx, items, userID)}
}

func (_c *MockURLUseCase_ShortenBatch_Call) Run(run func(ctx context.Context, items []BatchItem, userID string)) *MockURLUseCase_ShortenBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []BatchItem
		if args[1] != nil {
			arg1 = args[1].([]BatchItem)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockURLUseCase_ShortenBatch_Call) Return(batchResults []BatchResult, err error) *MockURLUseCase_ShortenBatch_Call {
	_c.Call.Return(batchResults, err)
	return _c
}

func (_c *MockURLUseCase_ShortenBatch_Call) RunAndReturn(run func(ctx context.Context, items []BatchItem, userID string) ([]BatchResult, error)) *MockURLUseCase_ShortenBatch_Call {
	_c.Call.Return(run)
	return _c
}
